// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ManifestClient is an autogenerated mock type for the ManifestClient type
type ManifestClient struct {
	mock.Mock
}

// DownloadFromSource provides a mock function with given fields: ctx, source, path
func (_m *ManifestClient) DownloadFromSource(ctx context.Context, source string, path string) (string, error) {
	ret := _m.Called(ctx, source, path)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, source, path)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, source, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
