// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	manifestival "github.com/manifestival/manifestival"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// HelmClient is an autogenerated mock type for the HelmClient type
type HelmClient struct {
	mock.Mock
}

// Template provides a mock function with given fields: ctx, releaseName, source, path, values
func (_m *HelmClient) Template(ctx context.Context, releaseName string, source string, path string, values *v1.JSON) (manifestival.Manifest, error) {
	ret := _m.Called(ctx, releaseName, source, path, values)

	var r0 manifestival.Manifest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *v1.JSON) manifestival.Manifest); ok {
		r0 = rf(ctx, releaseName, source, path, values)
	} else {
		r0 = ret.Get(0).(manifestival.Manifest)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *v1.JSON) error); ok {
		r1 = rf(ctx, releaseName, source, path, values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
