// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"

	v1alpha1 "github.com/ZupIT/charlescd-operator/api/v1alpha1"
)

// StatusWriter is an autogenerated mock type for the StatusWriter type
type StatusWriter struct {
	mock.Mock
}

// UpdateModuleStatus provides a mock function with given fields: ctx, _a1
func (_m *StatusWriter) UpdateModuleStatus(ctx context.Context, _a1 *v1alpha1.Module) (reconcile.Result, error) {
	ret := _m.Called(ctx, _a1)

	var r0 reconcile.Result
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Module) reconcile.Result); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(reconcile.Result)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.Module) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
