apiVersion: kuttl.dev/v1beta1
kind: TestSuite
kindContext: charlescd
kindNodeCache: true
skipClusterDelete: false
skipDelete: false
startKIND: true
commands:
  - command: make deploy
  - command: kubectl -n charlescd wait --timeout=60s --for=condition=Available deployment.apps/charlescd-operator
  - command: kubectl -n charlescd wait --timeout=60s --for=condition=Available deployment.apps/charlescd-flux-source-controller
testDirs: [ ./test/integration/ ]
kindContainers: [ "charlescd.io/charlescd-operator:0.0.1" ]
