// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controllers

import (
	"github.com/ZupIT/charlescd-operator/internal/client"
	"github.com/ZupIT/charlescd-operator/internal/object"
	"github.com/ZupIT/charlescd-operator/internal/resources"
	"github.com/ZupIT/charlescd-operator/internal/runtime"
	"github.com/ZupIT/charlescd-operator/pkg/filter"
	"github.com/ZupIT/charlescd-operator/pkg/module"
	"github.com/ZupIT/charlescd-operator/pkg/transformer"
	client2 "github.com/manifestival/controller-runtime-client"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

// Injectors from wire.go:

func createReconcilers(managerManager manager.Manager) ([]Reconciler, error) {
	clientClient := runtime.Client(managerManager)
	clientModule := client.NewModule(clientClient)
	status := module.NewStatus(clientModule)
	gitRepository := &filter.GitRepository{}
	filters := &module.Filters{
		GitRepository: gitRepository,
	}
	scheme := runtime.Scheme(managerManager)
	unstructuredConverter := &object.UnstructuredConverter{
		Scheme: scheme,
	}
	transformerGitRepository := transformer.NewGitRepository(unstructuredConverter)
	reference := &object.Reference{
		Scheme: scheme,
	}
	metadata := transformer.NewMetadata(reference)
	transformers := &module.Transformers{
		GitRepository: transformerGitRepository,
		Metadata:      metadata,
	}
	manifestivalClient := client2.NewClient(clientClient)
	manifests := &resources.Manifests{
		Client: manifestivalClient,
	}
	desiredState := module.NewDesiredState(filters, transformers, manifests)
	clientGitRepository := client.NewGitRepository(clientClient)
	artifactDownload := module.NewArtifactDownload(clientGitRepository, clientModule)
	helm := client.NewHelm(manifests)
	helmValidation := module.NewHelmValidation(helm, clientModule)
	kustomization := client.NewKustomization(manifests)
	kustomizationValidation := module.NewKustomizationValidation(kustomization, clientModule)
	checkComponents := module.NewCheckComponents(manifests, unstructuredConverter, clientModule)
	manifest := client.NewManifest(manifests)
	manifestValidation := module.NewManifestValidation(clientModule, manifest)
	moduleHandler := &ModuleHandler{
		Status:                  status,
		DesiredState:            desiredState,
		ArtifactDownload:        artifactDownload,
		HelmValidation:          helmValidation,
		KustomizationValidation: kustomizationValidation,
		CheckComponents:         checkComponents,
		ManifestValidation:      manifestValidation,
	}
	moduleReconciler := newModuleReconciler(moduleHandler, clientModule)
	v := reconcilers(moduleReconciler)
	return v, nil
}
