# permissions for end users to view modules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: module-viewer-role
rules:
- apiGroups:
  - deploy.charlescd.io
  resources:
  - modules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.charlescd.io
  resources:
  - modules/status
  verbs:
  - get
